version = 1

[[annotations]]
path = [
  "*.md",
  "**/*.md",
  ".gitignore",
  "REUSE.toml",
]
SPDX-FileCopyrightText = "2026 dieter8322-arch"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "LICENSE"
SPDX-FileCopyrightText = "2026 dieter8322-arch"
SPDX-License-Identifier = "MIT"
